config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                      controllers: {omniauth_callbacks: "omniauth_callbacks", :registrations => "registrations"}

  root :to => "application#home"

  resources :documents do
  end

  resources :users, only: :show do
    get "channel", to: 'users#channel', :as => "channel"
    get "videos", to: 'users#videos', :as => "videos"
    get "comments", to: 'users#comments', :as => "comments"
    get "about", to: 'users#about', :as => "about"
  end

    match "content/:id", :to => "application#content", :as => "content", via: 'get'

  match "channel/:id", :to => 'users#show', as: "channel", via: 'get'

  match "viewing", :to => 'medias#viewing', as: "viewing", via: 'get'

  resources :medias
  resource :medias, only: :index do
    get "popular", to: 'medias#popular', :as => "popular"
    get "recent", to: 'medias#recent', :as => "recent"
    get "category", to: 'medias#category', :as => "category"
  end

=begin
  match "medias/popular", :to => 'medias#popular', as: "popular", via: 'get'
=end

  resources :media_steps

  match "search", :to => 'application#search', as: "search", via: %w(get post)
  get "search", controller: "application", :only => [:show]

  get "playlists_management", :to => "playlists_management#show", as: "playlists_management", via: 'get'

  resources :playlists
  resources :category_of_playlists_channels

  resources :events

  match "quiz", :to => 'events#quiz', as: "quiz", via: %w(get post put)

  match "create_bin", controller: "events", via: ['get','post']
  match "modify_bin", controller: "events", via: ['get','post']

  match "media_timeline", controller: "events", via: ['get','post','destroy']

  resources :labels do
  end

  resources :bins, only: [:destroy]

  get "channel", controller: "application"

  get "category_plist_channels_api", controller: "users", :only => [:show], :defaults => { :format => 'json' }
  get "media_timeline_api", controller: "events", :only => [:show], :defaults => { :format => 'json' }

  match "discover", :to => 'application#discover', as: "discover", via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imsp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application.js' %>
  <!--<script type="text/javascript" src="//cdn.jsdelivr.net/clappr.playback-name/latest/playbackname.min.js"></script>
  <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
  <script type="text/javascript" src="http://cdn.jsdelivr.net/clappr.rtmp/0.0.2/rtmp.min.js"></script>
  <script type="text/javascript" charset="utf-8" src="./clappr_dash.js"></script>
  <script type="text/javascript" src="./assets/bower_components/angular/angular.js"></script>
  <script type="text/javascript" src="./bower_components/angular-sanitize/angular-sanitize.js"></script>
  <script type="text/javascript" src="./bower_components/extras.angular.plus/ngplus-overlay.js"></script>
  <script type="text/javascript" src="./bower_components/moment/moment.js"></script>
  <script type="text/javascript" src="./bower_components/angular-ui-router/release/angular-ui-router.js"></script>
  <script type="text/javascript" src="./bower_components/toastr/toastr.js"></script>
  <script type="text/javascript" src="./bower_components/angular-animate/angular-animate.js"></script>
  <script type="text/javascript" src="./bower_components/angular-translate/angular-translate.js"></script>
  <script type="text/javascript" src="./bower_components/angular-cookies/angular-cookies.js"></script>
  <script type="text/javascript" src="./bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js"></script>
  <script type="text/javascript" src="./bower_components/angular-translate-loader-partial/angular-translate-loader-partial.js"></script>
  <script type="text/javascript"src="./bower_components/angular-ui-select/dist/select.js"></script>
  <script type="text/javascript" src="./bower_components/dropzone/dist/min/dropzone.min.js"></script>-->
  <!--    <script src="/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
      <script src="/bower_components/angular-bootstrap/ui-bootstrap.min.js"></script>-->

  <%= csrf_meta_tags %>
</head>
<% if params[:action] != "content" %>
    <body>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to("IMSP", root_url, :class => "navbar-brand") %>
            <%= link_to("Discover", discover_url, :class => "navbar-brand") %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav videos_nav">
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">VIDEOS <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <% if user_signed_in? %>
                      <li><%= link_to 'Recommanded', "#" %></li>
                  <% end %>
                  <li><%= link_to 'Recently added', recent_medias_path %></li>
                  <li><%= link_to 'Popular', popular_medias_path %></li>
                  <li><%= link_to 'Category', category_medias_path %></li>
                </ul>
              </li>
            </ul>

            <% if user_signed_in? %>
                <ul class="nav navbar-nav user_nav">
                  <% if current_user.cover != nil %>
                      <li class="dropdown"><a href="#" class="dropdown-toggle user_cover_link" data-toggle="dropdown" role="button" aria-expanded="false"><%=image_tag("#{current_user.cover}",:class =>"user_cover")%> <span class="caret"></span></a>
                  <% else %>
                      <li class="dropdown"><a href="#" class="dropdown-toggle user_pseudo_link" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.pseudo %> <span class="caret"></span></a>
                  <% end %>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to 'My profile', user_channel_path(current_user) %></li>
                      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to 'My Channel', user_channel_path(current_user) %></li>
                      <li><%= link_to 'My videos', medias_path %></li>
                      <li><%= link_to 'My Playlists', playlists_path %></li>
                      <li><%= link_to 'My Categories', category_of_playlists_channels_path %></li>
                      <li><%= link_to 'My Events',events_path %></li>
                      <li><%= link_to 'My Subscriptions',events_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Log out", destroy_user_session_path, method: :delete  %></li>
                    </ul>
                  </li>
                </ul>
            <% else %>
                <div class="user-connexion">
                    <ul class="nav navbar-nav log_in_nav">
                      <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Log in <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to "Log in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
                          <li><%= link_to "Log in in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
                          <li class="divider"></li>
                          <li><%= link_to "Log in", new_user_session_path %></li>
                        </ul>
                      </li>
                    </ul>
                    <ul class="nav navbar-nav sign_in_nav">
                      <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign up <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><%= link_to "Sign up", new_user_registration_path %></li>
                        </ul>
                      </li>
                    </ul>
                </div>
            <% end %>
            <%= form_tag(controller: "application", action: "search", method: "post") do %>
                <div class="form-group search-form">
                  <%= text_field_tag(:query, "", :class =>"title-field")%>
                  <%= button_tag("Search", :class => "btn btn-default") %>
                </div>
            <% end %>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      <div class="container">

          <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, id: "flash_#{name}" %>
          <% end %>
          <%= yield %>


        <div ng-view></div>

      </div>

    </body>
<% else params[:action] == "content" %>
<body style="min-height: 100%;">
    <div style="position: absolute;width: 100%">
        <%= render partial: "content" %>
    </div>
</body>
<% end %>

</html>